const mapDetails = {
  canggu: {
    id: 'neighborhood.90123367',
    type: 'Feature',
    place_type: ['neighborhood'],
    relevance: 1,
    properties: {
      mapbox_id: 'dXJuOm1ieHBsYzpCVjhzWnc',
      wikidata: 'Q2543000',
    },
    'text_en-GB': 'Canggu',
    'language_en-GB': 'en',
    'place_name_en-GB': 'Canggu, 80363, Kuta, Badung, Bali, Indonesia',
    text: 'Canggu',
    language: 'en',
    place_name: 'Canggu, 80363, Kuta, Badung, Bali, Indonesia',
    bbox: [115.122894, -8.663184, 115.157501, -8.616365],
    center: [115.13651, -8.650193],
    geometry: {
      type: 'Point',
      coordinates: [115.13651, -8.650193],
    },
    context: [
      {
        id: 'postcode.80318055',
        mapbox_id: 'dXJuOm1ieHBsYzpCTW1PWnc',
        'text_en-GB': '80363',
        text: '80363',
      },
      {
        id: 'locality.22604391',
        mapbox_id: 'dXJuOm1ieHBsYzpBVmpxWnc',
        wikidata: 'Q994499',
        'text_en-GB': 'Kuta',
        'language_en-GB': 'en',
        text: 'Kuta',
        language: 'en',
      },
      {
        id: 'place.141415',
        mapbox_id: 'dXJuOm1ieHBsYzpBaWhu',
        wikidata: 'Q11482',
        'text_en-GB': 'Badung',
        'language_en-GB': 'en',
        text: 'Badung',
        language: 'en',
      },
      {
        id: 'region.91239',
        mapbox_id: 'dXJuOm1ieHBsYzpBV1Ju',
        wikidata: 'Q3125978',
        short_code: 'ID-BA',
        'text_en-GB': 'Bali',
        'language_en-GB': 'en',
        text: 'Bali',
        language: 'en',
      },
      {
        id: 'country.8807',
        mapbox_id: 'dXJuOm1ieHBsYzpJbWM',
        wikidata: 'Q252',
        short_code: 'id',
        'text_en-GB': 'Indonesia',
        'language_en-GB': 'en',
        text: 'Indonesia',
        language: 'en',
      },
    ],
  },
  seminyak: {
    id: 'neighborhood.473762919',
    type: 'Feature',
    place_type: ['neighborhood'],
    relevance: 1,
    properties: {
      mapbox_id: 'dXJuOm1ieHBsYzpIRDBNWnc',
      wikidata: 'Q1026424',
    },
    'text_en-GB': 'Seminyak',
    'language_en-GB': 'en',
    'place_name_en-GB': 'Seminyak, 80361, Kuta, Badung, Bali, Indonesia',
    text: 'Seminyak',
    language: 'en',
    place_name: 'Seminyak, 80361, Kuta, Badung, Bali, Indonesia',
    bbox: [115.150374, -8.697469, 115.180222, -8.682186],
    center: [115.16778, -8.691034],
    geometry: {
      type: 'Point',
      coordinates: [115.16778, -8.691034],
    },
    context: [
      {
        id: 'postcode.80301671',
        mapbox_id: 'dXJuOm1ieHBsYzpCTWxPWnc',
        'text_en-GB': '80361',
        text: '80361',
      },
      {
        id: 'locality.22489703',
        mapbox_id: 'dXJuOm1ieHBsYzpBVmNxWnc',
        wikidata: 'Q994499',
        'text_en-GB': 'Kuta',
        'language_en-GB': 'en',
        text: 'Kuta',
        language: 'en',
      },
      {
        id: 'place.141415',
        mapbox_id: 'dXJuOm1ieHBsYzpBaWhu',
        wikidata: 'Q11482',
        'text_en-GB': 'Badung',
        'language_en-GB': 'en',
        text: 'Badung',
        language: 'en',
      },
      {
        id: 'region.91239',
        mapbox_id: 'dXJuOm1ieHBsYzpBV1Ju',
        wikidata: 'Q3125978',
        short_code: 'ID-BA',
        'text_en-GB': 'Bali',
        'language_en-GB': 'en',
        text: 'Bali',
        language: 'en',
      },
      {
        id: 'country.8807',
        mapbox_id: 'dXJuOm1ieHBsYzpJbWM',
        wikidata: 'Q252',
        short_code: 'id',
        'text_en-GB': 'Indonesia',
        'language_en-GB': 'en',
        text: 'Indonesia',
        language: 'en',
      },
    ],
  },
  kuta: {
    id: 'locality.22489703',
    type: 'Feature',
    place_type: ['locality'],
    relevance: 1,
    properties: {
      mapbox_id: 'dXJuOm1ieHBsYzpBVmNxWnc',
      wikidata: 'Q994499',
    },
    'text_en-GB': 'Kuta',
    'language_en-GB': 'en',
    'place_name_en-GB': 'Kuta, Badung, Bali, Indonesia',
    text: 'Kuta',
    language: 'en',
    place_name: 'Kuta, Badung, Bali, Indonesia',
    bbox: [115.150374, -8.770729, 115.193935, -8.682186],
    center: [115.17325, -8.727787],
    geometry: {
      type: 'Point',
      coordinates: [115.17325, -8.727787],
    },
    context: [
      {
        id: 'place.141415',
        mapbox_id: 'dXJuOm1ieHBsYzpBaWhu',
        wikidata: 'Q11482',
        'text_en-GB': 'Badung',
        'language_en-GB': 'en',
        text: 'Badung',
        language: 'en',
      },
      {
        id: 'region.91239',
        mapbox_id: 'dXJuOm1ieHBsYzpBV1Ju',
        wikidata: 'Q3125978',
        short_code: 'ID-BA',
        'text_en-GB': 'Bali',
        'language_en-GB': 'en',
        text: 'Bali',
        language: 'en',
      },
      {
        id: 'country.8807',
        mapbox_id: 'dXJuOm1ieHBsYzpJbWM',
        wikidata: 'Q252',
        short_code: 'id',
        'text_en-GB': 'Indonesia',
        'language_en-GB': 'en',
        text: 'Indonesia',
        language: 'en',
      },
    ],
  },
  umalas: {
    id: 'neighborhood.umalas-bali',
    type: 'Feature',
    place_type: ['neighborhood'],
    relevance: 1,
    properties: {
      mapbox_id: 'dXJuOm1ieHBsYzpVbWFsYXM',
      wikidata: 'Q28123456',
    },
    'text_en-GB': 'Umalas',
    'language_en-GB': 'en',
    'place_name_en-GB': 'Umalas, 80361, Kerobokan Kelod, Badung, Bali, Indonesia',
    text: 'Umalas',
    language: 'en',
    place_name: 'Umalas, 80361, Kerobokan Kelod, Badung, Bali, Indonesia',
    bbox: [115.1483, -8.6743, 115.1683, -8.6503],
    center: [115.1583, -8.6623],
    geometry: {
      type: 'Point',
      coordinates: [115.1583, -8.6623],
    },
    context: [
      {
        id: 'postcode.80301671',
        mapbox_id: 'dXJuOm1ieHBsYzpCTWxPWnc',
        'text_en-GB': '80361',
        text: '80361',
      },
      {
        id: 'locality.kerobokan-kelod',
        mapbox_id: 'dXJuOm1ieHBsYzpLZXJvYm9rYW4',
        'text_en-GB': 'Kerobokan Kelod',
        'language_en-GB': 'en',
        text: 'Kerobokan Kelod',
        language: 'en',
      },
      {
        id: 'place.141415',
        mapbox_id: 'dXJuOm1ieHBsYzpBaWhu',
        wikidata: 'Q11482',
        'text_en-GB': 'Badung',
        'language_en-GB': 'en',
        text: 'Badung',
        language: 'en',
      },
      {
        id: 'region.91239',
        mapbox_id: 'dXJuOm1ieHBsYzpBV1Ju',
        wikidata: 'Q3125978',
        short_code: 'ID-BA',
        'text_en-GB': 'Bali',
        'language_en-GB': 'en',
        text: 'Bali',
        language: 'en',
      },
      {
        id: 'country.8807',
        mapbox_id: 'dXJuOm1ieHBsYzpJbWM',
        wikidata: 'Q252',
        short_code: 'id',
        'text_en-GB': 'Indonesia',
        'language_en-GB': 'en',
        text: 'Indonesia',
        language: 'en',
      },
    ],
  },
  denpasar: {
    id: 'place.878695',
    type: 'Feature',
    place_type: ['place'],
    relevance: 1,
    properties: {
      mapbox_id: 'dXJuOm1ieHBsYzpEV2hu',
      wikidata: 'Q11506',
    },
    'text_en-GB': 'Denpasar',
    'language_en-GB': 'en',
    'place_name_en-GB': 'Denpasar, Bali, Indonesia',
    text: 'Denpasar',
    language: 'en',
    place_name: 'Denpasar, Bali, Indonesia',
    bbox: [115.173806, -8.767891, 115.294877, -8.591523],
    center: [115.21312, -8.669399],
    geometry: {
      type: 'Point',
      coordinates: [115.21312, -8.669399],
    },
    context: [
      {
        id: 'region.91239',
        mapbox_id: 'dXJuOm1ieHBsYzpBV1Ju',
        wikidata: 'Q3125978',
        short_code: 'ID-BA',
        'text_en-GB': 'Bali',
        'language_en-GB': 'en',
        text: 'Bali',
        language: 'en',
      },
      {
        id: 'country.8807',
        mapbox_id: 'dXJuOm1ieHBsYzpJbWM',
        wikidata: 'Q252',
        short_code: 'id',
        'text_en-GB': 'Indonesia',
        'language_en-GB': 'en',
        text: 'Indonesia',
        language: 'en',
      },
    ],
  },
  pererean: {
    id: 'neighborhood.408464487',
    type: 'Feature',
    place_type: ['neighborhood'],
    relevance: 0.9375,
    properties: {
      mapbox_id: 'dXJuOm1ieHBsYzpHRmlzWnc',
      wikidata: 'Q12504938',
    },
    'text_en-GB': 'Pererenan',
    'language_en-GB': 'en',
    'place_name_en-GB': 'Pererenan, 80351, Mengwi, Badung, Bali, Indonesia',
    text: 'Pererenan',
    language: 'en',
    place_name: 'Pererenan, 80351, Mengwi, Badung, Bali, Indonesia',
    bbox: [115.117988, -8.652869, 115.142385, -8.627116],
    center: [115.13639, -8.63294],
    geometry: {
      type: 'Point',
      coordinates: [115.13639, -8.63294],
    },
    context: [
      {
        id: 'postcode.55488103',
        mapbox_id: 'dXJuOm1ieHBsYzpBMDZ1Wnc',
        'text_en-GB': '80351',
        text: '80351',
      },
      {
        id: 'locality.28133991',
        mapbox_id: 'dXJuOm1ieHBsYzpBYTFLWnc',
        'text_en-GB': 'Mengwi',
        text: 'Mengwi',
      },
      {
        id: 'place.141415',
        mapbox_id: 'dXJuOm1ieHBsYzpBaWhu',
        wikidata: 'Q11482',
        'text_en-GB': 'Badung',
        'language_en-GB': 'en',
        text: 'Badung',
        language: 'en',
      },
      {
        id: 'region.91239',
        mapbox_id: 'dXJuOm1ieHBsYzpBV1Ju',
        wikidata: 'Q3125978',
        short_code: 'ID-BA',
        'text_en-GB': 'Bali',
        'language_en-GB': 'en',
        text: 'Bali',
        language: 'en',
      },
      {
        id: 'country.8807',
        mapbox_id: 'dXJuOm1ieHBsYzpJbWM',
        wikidata: 'Q252',
        short_code: 'id',
        'text_en-GB': 'Indonesia',
        'language_en-GB': 'en',
        text: 'Indonesia',
        language: 'en',
      },
    ],
  },
  gianyar: {
    id: 'place.993383',
    type: 'Feature',
    place_type: ['place'],
    relevance: 1,
    properties: {
      mapbox_id: 'dXJuOm1ieHBsYzpEeWhu',
      wikidata: 'Q11496',
    },
    'text_en-GB': 'Gianyar',
    'language_en-GB': 'en',
    'place_name_en-GB': 'Gianyar, Bali, Indonesia',
    text: 'Gianyar',
    language: 'en',
    place_name: 'Gianyar, Bali, Indonesia',
    bbox: [115.225222, -8.671908, 115.376012, -8.313555],
    center: [115.2648, -8.510406],
    geometry: {
      type: 'Point',
      coordinates: [115.2648, -8.510406],
    },
    context: [
      {
        id: 'region.91239',
        mapbox_id: 'dXJuOm1ieHBsYzpBV1Ju',
        wikidata: 'Q3125978',
        short_code: 'ID-BA',
        'text_en-GB': 'Bali',
        'language_en-GB': 'en',
        text: 'Bali',
        language: 'en',
      },
      {
        id: 'country.8807',
        mapbox_id: 'dXJuOm1ieHBsYzpJbWM',
        wikidata: 'Q252',
        short_code: 'id',
        'text_en-GB': 'Indonesia',
        'language_en-GB': 'en',
        text: 'Indonesia',
        language: 'en',
      },
    ],
  },
  ubud: {
    id: 'locality.52111975',
    type: 'Feature',
    place_type: ['locality'],
    relevance: 0.96,
    properties: {
      mapbox_id: 'dXJuOm1ieHBsYzpBeHNxWnc',
    },
    'text_en-GB': 'Ubud',
    'place_name_en-GB': 'Ubud, Gianyar, Bali, Indonesia',
    text: 'Ubud',
    place_name: 'Ubud, Gianyar, Bali, Indonesia',
    bbox: [115.229752, -8.579091, 115.282347, -8.455028],
    center: [115.262474, -8.506872],
    geometry: {
      type: 'Point',
      coordinates: [115.262474, -8.506872],
    },
    context: [
      {
        id: 'place.993383',
        mapbox_id: 'dXJuOm1ieHBsYzpEeWhu',
        wikidata: 'Q11496',
        'text_en-GB': 'Gianyar',
        'language_en-GB': 'en',
        text: 'Gianyar',
        language: 'en',
      },
      {
        id: 'region.91239',
        mapbox_id: 'dXJuOm1ieHBsYzpBV1Ju',
        wikidata: 'Q3125978',
        short_code: 'ID-BA',
        'text_en-GB': 'Bali',
        'language_en-GB': 'en',
        text: 'Bali',
        language: 'en',
      },
      {
        id: 'country.8807',
        mapbox_id: 'dXJuOm1ieHBsYzpJbWM',
        wikidata: 'Q252',
        short_code: 'id',
        'text_en-GB': 'Indonesia',
        'language_en-GB': 'en',
        text: 'Indonesia',
        language: 'en',
      },
    ],
  },
};

export { mapDetails };
