const mapDetails = {
  canggu: {
    id: 'neighborhood.90123367',
    type: 'Feature',
    place_type: ['neighborhood'],
    relevance: 1,
    properties: {
      mapbox_id: 'dXJuOm1ieHBsYzpCVjhzWnc',
      wikidata: 'Q2543000',
    },
    'text_en-GB': 'Canggu',
    'language_en-GB': 'en',
    'place_name_en-GB': 'Canggu, 80363, Kuta, Badung, Bali, Indonesia',
    text: 'Canggu',
    language: 'en',
    place_name: 'Canggu, 80363, Kuta, Badung, Bali, Indonesia',
    bbox: [115.122894, -8.663184, 115.157501, -8.616365],
    center: [115.13651, -8.650193],
    geometry: {
      type: 'Point',
      coordinates: [115.13651, -8.650193],
    },
    context: [
      {
        id: 'postcode.80318055',
        mapbox_id: 'dXJuOm1ieHBsYzpCTW1PWnc',
        'text_en-GB': '80363',
        text: '80363',
      },
      {
        id: 'locality.22604391',
        mapbox_id: 'dXJuOm1ieHBsYzpBVmpxWnc',
        wikidata: 'Q994499',
        'text_en-GB': 'Kuta',
        'language_en-GB': 'en',
        text: 'Kuta',
        language: 'en',
      },
      {
        id: 'place.141415',
        mapbox_id: 'dXJuOm1ieHBsYzpBaWhu',
        wikidata: 'Q11482',
        'text_en-GB': 'Badung',
        'language_en-GB': 'en',
        text: 'Badung',
        language: 'en',
      },
      {
        id: 'region.91239',
        mapbox_id: 'dXJuOm1ieHBsYzpBV1Ju',
        wikidata: 'Q3125978',
        short_code: 'ID-BA',
        'text_en-GB': 'Bali',
        'language_en-GB': 'en',
        text: 'Bali',
        language: 'en',
      },
      {
        id: 'country.8807',
        mapbox_id: 'dXJuOm1ieHBsYzpJbWM',
        wikidata: 'Q252',
        short_code: 'id',
        'text_en-GB': 'Indonesia',
        'language_en-GB': 'en',
        text: 'Indonesia',
        language: 'en',
      },
    ],
  },
  seminyak: {
    id: 'neighborhood.473762919',
    type: 'Feature',
    place_type: ['neighborhood'],
    relevance: 1,
    properties: {
      mapbox_id: 'dXJuOm1ieHBsYzpIRDBNWnc',
      wikidata: 'Q1026424',
    },
    'text_en-GB': 'Seminyak',
    'language_en-GB': 'en',
    'place_name_en-GB': 'Seminyak, 80361, Kuta, Badung, Bali, Indonesia',
    text: 'Seminyak',
    language: 'en',
    place_name: 'Seminyak, 80361, Kuta, Badung, Bali, Indonesia',
    bbox: [115.150374, -8.697469, 115.180222, -8.682186],
    center: [115.16778, -8.691034],
    geometry: {
      type: 'Point',
      coordinates: [115.16778, -8.691034],
    },
    context: [
      {
        id: 'postcode.80301671',
        mapbox_id: 'dXJuOm1ieHBsYzpCTWxPWnc',
        'text_en-GB': '80361',
        text: '80361',
      },
      {
        id: 'locality.22489703',
        mapbox_id: 'dXJuOm1ieHBsYzpBVmNxWnc',
        wikidata: 'Q994499',
        'text_en-GB': 'Kuta',
        'language_en-GB': 'en',
        text: 'Kuta',
        language: 'en',
      },
      {
        id: 'place.141415',
        mapbox_id: 'dXJuOm1ieHBsYzpBaWhu',
        wikidata: 'Q11482',
        'text_en-GB': 'Badung',
        'language_en-GB': 'en',
        text: 'Badung',
        language: 'en',
      },
      {
        id: 'region.91239',
        mapbox_id: 'dXJuOm1ieHBsYzpBV1Ju',
        wikidata: 'Q3125978',
        short_code: 'ID-BA',
        'text_en-GB': 'Bali',
        'language_en-GB': 'en',
        text: 'Bali',
        language: 'en',
      },
      {
        id: 'country.8807',
        mapbox_id: 'dXJuOm1ieHBsYzpJbWM',
        wikidata: 'Q252',
        short_code: 'id',
        'text_en-GB': 'Indonesia',
        'language_en-GB': 'en',
        text: 'Indonesia',
        language: 'en',
      },
    ],
  },
  kuta: {
    id: 'locality.22489703',
    type: 'Feature',
    place_type: ['locality'],
    relevance: 1,
    properties: {
      mapbox_id: 'dXJuOm1ieHBsYzpBVmNxWnc',
      wikidata: 'Q994499',
    },
    'text_en-GB': 'Kuta',
    'language_en-GB': 'en',
    'place_name_en-GB': 'Kuta, Badung, Bali, Indonesia',
    text: 'Kuta',
    language: 'en',
    place_name: 'Kuta, Badung, Bali, Indonesia',
    bbox: [115.150374, -8.770729, 115.193935, -8.682186],
    center: [115.17325, -8.727787],
    geometry: {
      type: 'Point',
      coordinates: [115.17325, -8.727787],
    },
    context: [
      {
        id: 'place.141415',
        mapbox_id: 'dXJuOm1ieHBsYzpBaWhu',
        wikidata: 'Q11482',
        'text_en-GB': 'Badung',
        'language_en-GB': 'en',
        text: 'Badung',
        language: 'en',
      },
      {
        id: 'region.91239',
        mapbox_id: 'dXJuOm1ieHBsYzpBV1Ju',
        wikidata: 'Q3125978',
        short_code: 'ID-BA',
        'text_en-GB': 'Bali',
        'language_en-GB': 'en',
        text: 'Bali',
        language: 'en',
      },
      {
        id: 'country.8807',
        mapbox_id: 'dXJuOm1ieHBsYzpJbWM',
        wikidata: 'Q252',
        short_code: 'id',
        'text_en-GB': 'Indonesia',
        'language_en-GB': 'en',
        text: 'Indonesia',
        language: 'en',
      },
    ],
  },
  umalas: {
    id: 'neighborhood.605891687',
    type: 'Feature',
    place_type: ['neighborhood'],
    relevance: 1,
    properties: {
      mapbox_id: 'dXJuOm1ieHBsYzpKQjBzWnc',
      wikidata: 'Q14753647',
    },
    'text_en-GB': 'Umalawain',
    'language_en-GB': 'en',
    'place_name_en-GB': 'Umalawain, 85774, Weliman, Malaka Regency, East Nusa Tenggara, Indonesia',
    text: 'Umalawain',
    language: 'en',
    place_name: 'Umalawain, 85774, Weliman, Malaka Regency, East Nusa Tenggara, Indonesia',
    bbox: [124.854195, -9.666196, 124.868199, -9.65243],
    center: [124.859535, -9.661404],
    geometry: {
      type: 'Point',
      coordinates: [124.859535, -9.661404],
    },
    context: [
      {
        id: 'postcode.81251943',
        mapbox_id: 'dXJuOm1ieHBsYzpCTmZPWnc',
        'text_en-GB': '85774',
        text: '85774',
      },
      {
        id: 'locality.53848679',
        mapbox_id: 'dXJuOm1ieHBsYzpBeldxWnc',
        'text_en-GB': 'Weliman',
        text: 'Weliman',
      },
      {
        id: 'place.2000999',
        mapbox_id: 'dXJuOm1ieHBsYzpIb2hu',
        wikidata: 'Q4069046',
        'text_en-GB': 'Malaka Regency',
        'language_en-GB': 'en',
        text: 'Malaka Regency',
        language: 'en',
      },
      {
        id: 'region.189543',
        mapbox_id: 'dXJuOm1ieHBsYzpBdVJu',
        wikidata: 'Q5061',
        short_code: 'ID-NT',
        'text_en-GB': 'East Nusa Tenggara',
        'language_en-GB': 'en',
        text: 'East Nusa Tenggara',
        language: 'en',
      },
      {
        id: 'country.8807',
        mapbox_id: 'dXJuOm1ieHBsYzpJbWM',
        wikidata: 'Q252',
        short_code: 'id',
        'text_en-GB': 'Indonesia',
        'language_en-GB': 'en',
        text: 'Indonesia',
        language: 'en',
      },
    ],
  },
  denpasar: {
    id: 'place.878695',
    type: 'Feature',
    place_type: ['place'],
    relevance: 1,
    properties: {
      mapbox_id: 'dXJuOm1ieHBsYzpEV2hu',
      wikidata: 'Q11506',
    },
    'text_en-GB': 'Denpasar',
    'language_en-GB': 'en',
    'place_name_en-GB': 'Denpasar, Bali, Indonesia',
    text: 'Denpasar',
    language: 'en',
    place_name: 'Denpasar, Bali, Indonesia',
    bbox: [115.173806, -8.767891, 115.294877, -8.591523],
    center: [115.21312, -8.669399],
    geometry: {
      type: 'Point',
      coordinates: [115.21312, -8.669399],
    },
    context: [
      {
        id: 'region.91239',
        mapbox_id: 'dXJuOm1ieHBsYzpBV1Ju',
        wikidata: 'Q3125978',
        short_code: 'ID-BA',
        'text_en-GB': 'Bali',
        'language_en-GB': 'en',
        text: 'Bali',
        language: 'en',
      },
      {
        id: 'country.8807',
        mapbox_id: 'dXJuOm1ieHBsYzpJbWM',
        wikidata: 'Q252',
        short_code: 'id',
        'text_en-GB': 'Indonesia',
        'language_en-GB': 'en',
        text: 'Indonesia',
        language: 'en',
      },
    ],
  },
  pererean: {
    id: 'neighborhood.408464487',
    type: 'Feature',
    place_type: ['neighborhood'],
    relevance: 0.9375,
    properties: {
      mapbox_id: 'dXJuOm1ieHBsYzpHRmlzWnc',
      wikidata: 'Q12504938',
    },
    'text_en-GB': 'Pererenan',
    'language_en-GB': 'en',
    'place_name_en-GB': 'Pererenan, 80351, Mengwi, Badung, Bali, Indonesia',
    text: 'Pererenan',
    language: 'en',
    place_name: 'Pererenan, 80351, Mengwi, Badung, Bali, Indonesia',
    bbox: [115.117988, -8.652869, 115.142385, -8.627116],
    center: [115.13639, -8.63294],
    geometry: {
      type: 'Point',
      coordinates: [115.13639, -8.63294],
    },
    context: [
      {
        id: 'postcode.55488103',
        mapbox_id: 'dXJuOm1ieHBsYzpBMDZ1Wnc',
        'text_en-GB': '80351',
        text: '80351',
      },
      {
        id: 'locality.28133991',
        mapbox_id: 'dXJuOm1ieHBsYzpBYTFLWnc',
        'text_en-GB': 'Mengwi',
        text: 'Mengwi',
      },
      {
        id: 'place.141415',
        mapbox_id: 'dXJuOm1ieHBsYzpBaWhu',
        wikidata: 'Q11482',
        'text_en-GB': 'Badung',
        'language_en-GB': 'en',
        text: 'Badung',
        language: 'en',
      },
      {
        id: 'region.91239',
        mapbox_id: 'dXJuOm1ieHBsYzpBV1Ju',
        wikidata: 'Q3125978',
        short_code: 'ID-BA',
        'text_en-GB': 'Bali',
        'language_en-GB': 'en',
        text: 'Bali',
        language: 'en',
      },
      {
        id: 'country.8807',
        mapbox_id: 'dXJuOm1ieHBsYzpJbWM',
        wikidata: 'Q252',
        short_code: 'id',
        'text_en-GB': 'Indonesia',
        'language_en-GB': 'en',
        text: 'Indonesia',
        language: 'en',
      },
    ],
  },
  gianyar: {
    id: 'place.993383',
    type: 'Feature',
    place_type: ['place'],
    relevance: 1,
    properties: {
      mapbox_id: 'dXJuOm1ieHBsYzpEeWhu',
      wikidata: 'Q11496',
    },
    'text_en-GB': 'Gianyar',
    'language_en-GB': 'en',
    'place_name_en-GB': 'Gianyar, Bali, Indonesia',
    text: 'Gianyar',
    language: 'en',
    place_name: 'Gianyar, Bali, Indonesia',
    bbox: [115.225222, -8.671908, 115.376012, -8.313555],
    center: [115.2648, -8.510406],
    geometry: {
      type: 'Point',
      coordinates: [115.2648, -8.510406],
    },
    context: [
      {
        id: 'region.91239',
        mapbox_id: 'dXJuOm1ieHBsYzpBV1Ju',
        wikidata: 'Q3125978',
        short_code: 'ID-BA',
        'text_en-GB': 'Bali',
        'language_en-GB': 'en',
        text: 'Bali',
        language: 'en',
      },
      {
        id: 'country.8807',
        mapbox_id: 'dXJuOm1ieHBsYzpJbWM',
        wikidata: 'Q252',
        short_code: 'id',
        'text_en-GB': 'Indonesia',
        'language_en-GB': 'en',
        text: 'Indonesia',
        language: 'en',
      },
    ],
  },
  ubud: {
    id: 'locality.52111975',
    type: 'Feature',
    place_type: ['locality'],
    relevance: 0.96,
    properties: {
      mapbox_id: 'dXJuOm1ieHBsYzpBeHNxWnc',
    },
    'text_en-GB': 'Ubud',
    'place_name_en-GB': 'Ubud, Gianyar, Bali, Indonesia',
    text: 'Ubud',
    place_name: 'Ubud, Gianyar, Bali, Indonesia',
    bbox: [115.229752, -8.579091, 115.282347, -8.455028],
    center: [115.262474, -8.506872],
    geometry: {
      type: 'Point',
      coordinates: [115.262474, -8.506872],
    },
    context: [
      {
        id: 'place.993383',
        mapbox_id: 'dXJuOm1ieHBsYzpEeWhu',
        wikidata: 'Q11496',
        'text_en-GB': 'Gianyar',
        'language_en-GB': 'en',
        text: 'Gianyar',
        language: 'en',
      },
      {
        id: 'region.91239',
        mapbox_id: 'dXJuOm1ieHBsYzpBV1Ju',
        wikidata: 'Q3125978',
        short_code: 'ID-BA',
        'text_en-GB': 'Bali',
        'language_en-GB': 'en',
        text: 'Bali',
        language: 'en',
      },
      {
        id: 'country.8807',
        mapbox_id: 'dXJuOm1ieHBsYzpJbWM',
        wikidata: 'Q252',
        short_code: 'id',
        'text_en-GB': 'Indonesia',
        'language_en-GB': 'en',
        text: 'Indonesia',
        language: 'en',
      },
    ],
  },
};

export { mapDetails };
